[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "pyo3-ffi-array-benchmark"
version = "0.1.0"
requires-python = ">=3.11"

[tool.maturin]
module-name = "pyo3_ffi_array_benchmark"
